services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./:/src/
      - ~/.gitconfig:/.gitconfig
      - ~/.ssh/:/.ssh/
      - vscode_extension:/home/user/.vscode-server/extensions
    tty: true
volumes:
  vscode_extension:
