name: "App token"
description: "get app token"

inputs:
  github_key_pem_base64:
    description: "Base64 encoded GitHub App private key PEM"
    required: false
    default: ""
  github_app_id:
    description: "GitHub App ID"
    required: true
  github_key_pem:
    description: "GitHub App private key"
    required: false
    default: ""


outputs:
  github_token:
    description: "Generated GitHub token"
    value: ${{ steps.generate-token.outputs.token }}

runs:
  using: "composite"
  steps:
    - name: decode key_pem
      uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
      id: decode
      if: ${{ inputs.github_key_pem_base64 != '' }}
      with:
        script: |
          const decoded = Buffer.from('${{ inputs.github_key_pem_base64 }}', 'base64');
          core.setOutput('decoded', decoded.toString());
          core.setSecret(decoded.toString());

    - name: Generate token
      uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
      id: generate-token
      with:
        app-id: ${{ inputs.github_app_id }}
        private-key: ${{ steps.decode.outputs.decoded || inputs.github_key_pem }}
        owner: ${{ github.repository_owner }}
