name: CI test

on:
  pull_request:
    paths:
      - 'lib/**'
      - '.github/workflows/test.yaml'

env:
  CI: true

jobs:
  unit-test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        go-version: ["1.24"]
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: Run Unit tests
        run: make unit-test-module
